### ISSUE TITLE
Question not issue - Addon Vehicles?

### ISSUE THREAD

**Issue by Agony099** [schwim0341/esx_trunk#16]
Hey Schwim, is there a way to change addon vehicle trunks? I tried adding them into the config but not having any luck so far

**Comment by schwim0341** [comment]
I'm not sure what issue you're having Agony, as our addon vehicles work both based on vehicle class and model override.  If you can provide more information, perhaps I could make a better guess.  What happens when you try?  What messages do you get exactly?  What, if anything do you get in server terminal and F8 right after trying?

**Comment by Agony099** [comment]
I may just have to rename the vehicle, it's just 1 vehicle that is named 1500dj but lua is only seeming to read the "1500d" because that portion is orange and the j is normal coloring, its a strange one

**Comment by schwim0341** [comment]
Can you post a screenie of what you mean by the coloring of the text?

**Comment by Agony099** [comment]
https://i.imgur.com/K8h12Tg.png

**Comment by schwim0341** [comment]
just for shits and giggles, try placing 1500dj in singlequotes and see what happens.

**Comment by MateoCodeScripts** [comment]
Same problem...
