### ISSUE TITLE
Doesn't Affect Personal Inventory

### ISSUE THREAD

**Issue by Janicki92** [schwim0341/esx_trunk#8]
The resource implies that it will restrict personal inventories to 25kg by default, but personal inventories do not seem to have any weight limits, rather still going off of the "items" limit in the DB.

**Comment by schwim0341** [comment]
There is no personal inventory limitation in this script since it's a trunk script and not a trunk & personal inventory script.  That commenting was put in by prior author I'm guessing either to give an idea of carrying capacity sanity checks or because he did have an inventory limit mechanism in place.
